---
- import_tasks: init.env.yml

- import_tasks: init.fetch.yml

- name: redis -> compile
  make:
    target: all
    chdir: '{{ var_runtime_folder }}/{{ var_redis_dir }}'

- name: redis -> install
  make:
    target: install
    chdir: '{{ var_runtime_folder }}/{{ var_redis_dir }}'
