---
- name: openresty -> link
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: /usr/local/openresty/bin/resty , dest: /usr/local/bin/resty }
    - { src: /usr/local/openresty/bin/openresty , dest: /usr/local/bin/nginx }
    - { src: /usr/local/openresty/luajit/bin/luajit , dest: /usr/local/bin/luajit }
