---
# openresty
- name: openresty -> fetch env
  stat:
    path: '{{ var_runtime_folder }}/{{ var_openresty_name }}'
    checksum_algorithm: sha256
  register: var_openresty

- block:
  - name: openresty -> upload
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
      - { src: '{{ var_openresty_name }}', dest: '{{ var_runtime_folder }}' }
    when: 
      - var_remote_fetch == false

  - name: openresty -> download
    get_url:
      url: '{{ item.url }}'
      dest: '{{ item.dest }}'
      checksum: sha256:{{ item.checksum }}
      mode: 0644
      timeout: 60
    with_items:
      - { url: '{{ var_openresty_url_download }}', dest: '{{ var_runtime_folder }}', checksum: '{{ var_openresty_check_sum_256 }}' }
    when:
      - var_remote_fetch != false

  when:
    - var_openresty.stat.exists == false or var_openresty.stat.checksum != var_openresty_check_sum_256


# openresty -> openssl
- name: openresty -> openssl -> fetch env
  stat:
    path: '{{ var_runtime_folder }}/{{ var_openssl_name }}'
    checksum_algorithm: sha256
  register: var_openssl

- block:
  - name: openresty -> openssl -> upload
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
      - { src: '{{ var_openssl_name }}', dest: '{{ var_runtime_folder }}' }
    when:
      - var_remote_fetch == false

  - name: openresty -> openssl -> download
    get_url:
      url: '{{ item.url }}'
      dest: '{{ item.dest }}'
      checksum: sha256:{{ item.checksum }}
      mode: 0644
      timeout: 60
    with_items:
      - { url: '{{ var_openssl_url_download }}', dest: '{{ var_runtime_folder }}', checksum: '{{ var_openssl_check_sum_256 }}' }
    when:
      - var_remote_fetch != false
      
  when:
    - var_openssl.stat.exists == false or var_openssl.stat.checksum != var_openssl_check_sum_256


# openresty -> pcre
- name: openresty -> pcre -> fetch env
  stat:
    path: '{{ var_runtime_folder }}/{{ var_pcre_name }}'
    checksum_algorithm: sha256
  register: var_pcre

- block:
  - name: openresty -> pcre -> upload
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
      - { src: '{{ var_pcre_name }}', dest: '{{ var_runtime_folder }}' }
    when:
      - var_remote_fetch == false

  - name: openresty -> pcre -> download
    get_url:
      url: '{{ item.url }}'
      dest: '{{ item.dest }}'
      checksum: sha256:{{ item.checksum }}
      mode: 0644
      timeout: 60
    with_items:
      - { url: '{{ var_pcre_url_download }}', dest: '{{ var_runtime_folder }}', checksum: '{{ var_pcre_check_sum_256 }}' }
    when:
      - var_remote_fetch != false

  when:
    - var_pcre.stat.exists == false or var_pcre.stat.checksum != var_pcre_check_sum_256


# extract
- name: openresty -> extract
  unarchive:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    remote_src: yes
  with_items:
    - { name: 'openresty', src: '{{ var_runtime_folder }}/{{ var_openresty_name }}', dest: '{{ var_runtime_folder }}' }
    - { name: 'openresty -> pcre', src: '{{ var_runtime_folder }}/{{ var_pcre_name }}', dest: '{{ var_runtime_folder }}/{{ var_openresty_bundle_dir }}' }
    - { name: 'openresty -> openssl', src: '{{ var_runtime_folder }}/{{ var_openssl_name }}', dest: '{{ var_runtime_folder }}/{{ var_openresty_bundle_dir }}' }
