---
- name: system -> init env
  yum:
    name: '{{ item.name }}'
    state: present
  with_items:
    # base
    - { name: epel-release }
    - { name: dkms }

    # builder
    - { name: make }
    - { name: cmake }

    # compiler
    - { name: gcc }
    - { name: gcc-c++ }

    - { name: patch }
    - { name: perl }

    # OS
    - { name: htop }
    - { name: iotop }
    - { name: nload}
    - { name: screen }
    - { name: net-tools }

    # software -> base
    - { name: curl }
    - { name: wget }
    - { name: unzip }
