---
- name: system -> init env
  yum:
    name: '{{ item.name }}'
    state: present
  with_items:
    # base
    - { name: epel-release }
    - { name: yum-utils }
    - { name: dkms }

    # system common libs
    # - { name: 'kernel-headers-{{ ansible_facts.kernel }}' }
    # - { name: 'kernel-devel-{{ ansible_facts.kernel }}' }

    # builder
    - { name: make }
    - { name: cmake }

    # compiler
    - { name: gcc }
    - { name: gcc-c++ }

    - { name: patch }
    - { name: perl }

    # OS monitor
    - { name: htop }
    - { name: lsof }
    - { name: iotop }
    - { name: nload }
    - { name: screen }
    - { name: net-tools }

    # software -> base
    - { name: curl }
    - { name: wget }
    - { name: unzip }
