---
- name: system -> info
  debug:
    msg:
      - 'OS: {{ ansible_distribution }} -> {{ ansible_distribution_version }}'
      - 'IP: {{ ansible_default_ipv4.address }}'
      - 'Remote fetch: {{ var_remote_fetch }}'
      - 'RT_Folder: {{ var_runtime_folder }}'
