---
- import_tasks: init.sys.info.yml

- import_tasks: init.sys.env.yml

- import_tasks: init.sys.time.yml

- import_tasks: init.sys.limit.yml

- import_tasks: init.sys.ctl.yml

- import_tasks: init.sys.swap.yml

- import_tasks: init.firewall.yml

- name: create runtime folder
  file:
    path: '{{ var_runtime_folder }}'
    state: directory
    mode: '0644'
  notify:
    - system -> clean
  changed_when: True
