---
- name: docker -> fecth env
  stat:
    path: '{{ var_runtime_folder }}/{{ var_docker_ce_name }}'
    checksum_algorithm: sha256
  register: var_docker

- name: docker -> docker-compose -> fecth env
  stat:
    path: '{{ var_runtime_folder }}/{{ var_docker_docker_compose_name }}'
    checksum_algorithm: sha256
  register: var_docker_compose

- name: docker -> upload -> detect
  set_fact:
    var_upload: true
  when:
    - var_docker.stat.exists == false or var_docker.stat.checksum != var_docker_ce_check_sum_256

- name: docker -> upload -> docker-compose 
  set_fact:
    var_upload: true
  when:
    - var_docker_compose.stat.exists == false or var_docker_compose.stat.checksum != var_docker_compose_check_sum_256
    
- block:
  - name: docker -> upload
    copy:
      src: '{{ item.src }}'
      dest: '{{ item.dest }}'
    with_items:
      - { src: '{{ var_docker_ce_name }}', dest: '{{ var_runtime_folder }}' }
      - { src: '{{ var_docker_ce_cli_name }}', dest: '{{ var_runtime_folder }}' }
      - { src: '{{ var_docker_containerd_name }}', dest: '{{ var_runtime_folder }}' }
      - { src: '{{ var_docker_docker_compose_name }}', dest: '{{ var_runtime_folder }}' }
    when:
      - var_remote_fetch == false

  - name: docker -> download
    get_url:
      url: '{{ item.url }}'
      dest: '{{ item.dest }}'
      checksum: sha256:{{ item.checksum }}
      mode: 0644
      timeout: 60
    with_items:
      - { url: '{{ var_docker_url }}/{{ var_docker_ce_name }}', dest: '{{ var_runtime_folder }}', checksum: '{{ var_docker_ce_check_sum_256 }}' }
      - { url: '{{ var_docker_url }}/{{ var_docker_ce_cli_name }}', dest: '{{ var_runtime_folder }}', checksum: '{{ var_docker_ce_cli_check_sum_256 }}' }
      - { url: '{{ var_docker_url }}/{{ var_docker_containerd_name }}', dest: '{{ var_runtime_folder }}', checksum: '{{ var_docker_containerd_check_sum_256 }}' }
      - { url: '{{ var_docker_compose_url }}/{{ var_docker_docker_compose_name }}', dest: '{{ var_runtime_folder }}', checksum: '{{ var_docker_compose_check_sum_256 }}' } 
    when:
      - var_remote_fetch != false

  when:
    - var_upload is defined
