---
- block:
  - name: docker -> group -> jenkins -> fetch env
    getent:
      database: passwd
      key: jenkins
      fail_key: no

  - name: docker -> group -> jenkins -> join
    user:
      name: jenkins
      groups: docker
      append: yes
    notify:
      - docker -> restart
    when: getent_passwd.jenkins is not none
