---
- import_tasks: init.fetch.yml

- name: docker -> install
  yum:
    name:
      - '{{ var_runtime_folder }}/{{ var_docker_containerd_name }}'
      - '{{ var_runtime_folder }}/{{ var_docker_ce_cli_name }}'
      - '{{ var_runtime_folder }}/{{ var_docker_ce_name }}'
    state: present
  notify:
    - docker -> restart

- name: docker -> docker-compose -> install
  copy:
    src: '{{ var_runtime_folder }}/{{ var_docker_docker_compose_name }}'
    dest: '/usr/bin/docker-compose'
    mode: '0755'
    remote_src: yes

- name: docker -> launch
  service:
    name: docker
    state: started
    enabled: yes

- import_tasks: init.config.yml
